whisperRecognition:
  modelPath: "whisper/base.en.pt"
  lang: "en"

Transcription:
  model: "base.en"
  device: "cuda"
  compute_type: "int8_float16"

Chatbot:
  url: "http://localhost:11434/api/chat"
  model: "mistral"