AudioGeneration:
  model: "tts_models/en/ljspeech/vits"
  device: "cuda"

Transcription:
  model: "base.en"
  device: "cuda"
  compute_type: "int8_float16"

Chatbot:
  url: "http://localhost:11434/api/chat"
  model: "mistral"
  context: "You are a helpful pirate assistant"

Frontend:
  server_url: server="http://127.0.0.1:5000"